import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# PAGE CONFIG


st.set_page_config(
    page_title="Network Intelligence Platform",
    page_icon="🛡️",
    layout="wide"
)

# LOAD DATA


@st.cache_data
def load_data():

    features = pd.read_csv(
        "data/traffic_features.csv"
    )

    forecasts = pd.read_csv(
        "data/traffic_forecasts.csv"
    )

    risks = pd.read_csv(
        "data/risk_scores.csv"
    )

    raw_df = pd.read_csv(
        "data/cs448b_ipasn.csv"
    )

    return features, forecasts, risks, raw_df


features, forecasts, risks,raw_df = load_data()

features['date'] = pd.to_datetime(features['date'])

if 'ds' in forecasts.columns:
    forecasts['ds'] = pd.to_datetime(
        forecasts['ds']
    )


# HEADER


st.title(
    "🛡️Network Traffic Anomaly Detection & Early Warning Platform"
)

st.markdown("""
This platform monitors workstation traffic, identifies abnormal behavior,
forecasts a 7-Day expected traffic baseline, and prioritizes high-risk assets
for proactive investigation.
""")

# SIDEBAR

st.sidebar.header("Filters")

selected_ws = st.sidebar.selectbox(
    "Select Workstation",
    sorted(features['l_ipn'].unique())
)

# EXECUTIVE OVERVIEW

st.header("📊 Executive Overview")

total_traffic = features['f'].sum()

total_anomalies = int(
    features['anomaly'].sum()
)

avg_risk = round(
    risks['risk_score'].mean(),
    2
)

highest_risk = (
    risks.sort_values(
        'risk_score',
        ascending=False
    )
    .iloc[0]['l_ipn']
)

col1,col2,col3,col4 = st.columns(4)

col1.metric(
    "Total Traffic",
    f"{total_traffic:,.0f}"
)

col2.metric(
    "Detected Anomalies",
    total_anomalies
)

col3.metric(
    "Average Risk Score",
    avg_risk
)

col4.metric(
    "Highest Risk Asset",
    int(highest_risk)
)

st.divider()


# TOP RISK ASSETS

st.header("🚨 Top Risk Assets")

top5 = (
    risks.sort_values(
        'risk_score',
        ascending=False
    )
    .head(5)
)

st.dataframe(
    top5,
    use_container_width=True
)

# RISK RANKING

st.header("🎯 Workstation Risk Ranking")

risk_rank = (
    risks.sort_values(
        'risk_score',
        ascending=False
    )
)

fig = px.bar(
    risk_rank,
    x='l_ipn',
    y='risk_score',
    color='risk_score',
    text='risk_score'
)

fig.update_layout(
    xaxis_title="Workstation",
    yaxis_title="Risk Score"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()


# TRAFFIC BY WORKSTATION

st.header("📈 Traffic Generated by Workstation")

traffic_summary = (
    features.groupby('l_ipn')['f']
    .sum()
    .reset_index()
)

fig = px.bar(
    traffic_summary,
    x='l_ipn',
    y='f',
    text='f'
)

fig.update_layout(
    xaxis_title="Workstation",
    yaxis_title="Total Flows"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

# ASN COMMUNICATION INTELLIGENCE


st.header("🌍 ASN Communication Intelligence")

col1, col2 = st.columns(2)


# ASN Diversity Per Workstation

asn_diversity = (
    raw_df.groupby('l_ipn')['r_asn']
    .nunique()
    .reset_index()
)

asn_diversity.columns = [
    'l_ipn',
    'unique_asns'
]

fig = px.bar(
    asn_diversity,
    x='l_ipn',
    y='unique_asns',
    text='unique_asns',
    title='Unique ASN Diversity per Workstation',
    labels={'r_asn': 'Unique Remote ASNs','l_ipn':'Workstations'}
)

col1.plotly_chart(
    fig,
    use_container_width=True
)


# Top External ASNs

top_asns = (
    raw_df.groupby('r_asn')['f']
    .sum()
    .reset_index()
    .sort_values(
        'f',
        ascending=False
    )
    .head(10)
)

fig = px.bar(
    top_asns,
    x='r_asn',
    y='f',
    text='f',
    title='Top External ASNs by Traffic',
    color_continuous_scale='Oranges',
    labels={'r_asn': 'Unique Remote ASNs','f':'Flows'}

)

col2.plotly_chart(
    fig,
    use_container_width=True
)


# ASN Diversity Trend

daily_asn = (
    raw_df.groupby(
        ['date', 'l_ipn']
    )['r_asn']
    .nunique()
    .reset_index()
)

daily_asn.columns = [
    'date',
    'l_ipn',
    'asn_count'
]

ws_asn = daily_asn[
    daily_asn['l_ipn']
    ==
    selected_ws
]

fig = px.line(
    ws_asn,
    x='date',
    y='asn_count',
    title=f'ASN Diversity Trend - Workstation {selected_ws}'
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Unique ASNs"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.info(
    "A sudden increase in ASN diversity may indicate unusual communication behaviour or possible compromise."
)

st.divider()


# NETWORK TRAFFIC TRENDS

st.header("📉 Network Traffic Trends")

traffic_trend = (
    features.pivot_table(
        index='date',
        columns='l_ipn',
        values='f'
    )
)

fig = px.line(
    traffic_trend
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Flows"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()


# WORKSTATION ANALYSIS

st.header(
    f"🖥️ Workstation {selected_ws} Analysis"
)

ws_data = (
    features[
        features['l_ipn']
        ==
        selected_ws
    ]
)

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=ws_data['date'],
        y=ws_data['f'],
        name='Traffic'
    )
)

fig.add_trace(
    go.Scatter(
        x=ws_data['date'],
        y=ws_data['rolling_mean'],
        name='Rolling Mean'
    )
)

fig.add_trace(
    go.Scatter(
        x=ws_data['date'],
        y=ws_data['upper_limit'],
        name='Threshold'
    )
)

fig.update_layout(
    title="Traffic Behaviour"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()


# ANOMALY DETECTION

st.header("⚠️ Statistical Anomaly Detection")

anomalies = (
    ws_data[
        ws_data['anomaly']
    ]
)

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=ws_data['date'],
        y=ws_data['f'],
        mode='lines',
        name='Traffic'
    )
)

fig.add_trace(
    go.Scatter(
        x=anomalies['date'],
        y=anomalies['f'],
        mode='markers',
        name='Anomaly',
        marker=dict(
            color='red',
            size=10
        )
    )
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()


# ISOLATION FOREST


if 'anomaly_isoforest' in features.columns:

    st.header(
        " Behavioral Anomaly Detection"
    )

    iso_counts = (
        features.groupby('l_ipn')
        ['anomaly_isoforest']
        .sum()
        .reset_index()
    )

    fig = px.bar(
        iso_counts,
        x='l_ipn',
        y='anomaly_isoforest',
        text='anomaly_isoforest'
    )

    fig.update_layout(
        xaxis_title="Workstation",
        yaxis_title="Isolation Forest Alerts"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

st.divider()


# FORECASTING

st.header("7-Day Expected Traffic Forecast")

ws_forecast = (
    forecasts[
        forecasts['l_ipn']
        ==
        selected_ws
    ]
)

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=ws_forecast['ds'],
        y=ws_forecast['yhat'],
        name='Forecast'
    )
)

fig.add_trace(
    go.Scatter(
        x=ws_forecast['ds'],
        y=ws_forecast['yhat_upper'],
        name='Upper Bound'
    )
)

fig.add_trace(
    go.Scatter(
        x=ws_forecast['ds'],
        y=ws_forecast['yhat_lower'],
        name='Lower Bound'
    )
)

fig.update_layout(
    title=f"Forecast - Workstation {selected_ws}"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()

# OPERATIONAL RECOMMENDATIONS

st.header("📋 Operational Recommendations")

st.info(f"""
Highest Risk Workstation: {highest_risk}

Recommendations:

• High risk workstation should be prioritized for immediate investigation such as workstation {highest_risk} for instance.

• Deviations from expected traffic patterns should be monitored closely for early signs of compromise alerting security teams to investigate potential issues before they escalate.

• Continuous automated monitoring should reduce dependence on user-reported incidents through predictive detection.

• ASN communication patterns should be analyzed for unusual diversity spikes or connections to high-risk ASNs, which may indicate data exfiltration or command-and-control activity.
""")

# FOOTER


st.markdown("---")

st.caption(
    "Built using Python, PostgreSQL, Streamlit, Plotly, Isolation Forest and Prophet"
)
st.caption(
    "Author: Bantar Harris Ndzi"
)